### ISSUE TITLE
[1.5.0] Express app doesn't work anymore

### ISSUE THREAD

**Issue by MaksJS** [jashkenas/coffeescript#2714]
For example

``` coffeescript
express      = require 'express'
mongoose     = require 'mongoose'
{simple_mvc} = require 'express-simple-mvc'
require 'namespace'

app = express()
app.listen 3000

app.configure ->
  app.use express.methodOverride()
  app.use app.router

simple_mvc app, __dirname + '/controllers', __dirname + '/models', __dirname + '/config/routes'

mongoose.connect 'mongodb://127.0.0.1:27017/test', (err) -> 
  if err then throw err
```

Will throw a TypeError

```
TypeError: object is not a function
    at Object.<anonymous> (C:\Users\Maxence\Dropbox\fantasy-universe\beta\vendor
\node_modules\express-simple-mvc\example\app.coffee:12:9)
    at Object.<anonymous> (C:\Users\Maxence\Dropbox\fantasy-universe\beta\vendor
\node_modules\express-simple-mvc\example\app.coffee:29:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (C:\Users\Maxence\AppData\Roaming\npm\node_modules\cof
fee-script\lib\coffee-script\coffee-script.js:82:25)
    at compileScript (C:\Users\Maxence\AppData\Roaming\npm\node_modules\coffee-s
cript\lib\coffee-script\command.js:177:29)
    at fs.stat.notSources.(anonymous function) (C:\Users\Maxence\AppData\Roaming
\npm\node_modules\coffee-script\lib\coffee-script\command.js:152:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

Worked well with CS 1.4.0
